### ISSUE TITLE
ERT 1.11.10 errors for syslog_scheduler configuration 

### ISSUE THREAD

**Issue by kamoljan** [c0-ops/ert-concourse#8]
Hi guys!

I am trying to use ERT 1.11.10 and the configuration below 
https://github.com/pivotal-cf/ert-concourse/blob/5091e56cee2ff257275c7fb265e55fc7a8b0a4fe/json_templates/azure/c0-azure-base/ert-template.json#L388-L394

Outputs the follow error:
```
---------------------------------------------------------------------------------------------
Setting syslog_adapter-38aacdbf3a887d2433ac with --data={"instance_type":{"id":"automatic"},"instances":1,"elb_names":[]}...
{}
---------------------------------------------------------------------------------------------
Setting syslog_scheduler-54dfb21545956129c352 with --data={"instance_type":{"id":"automatic"},"instances":1,"elb_names":[]}...
ERROR
stdout:n
{
  "errors": {
    "instances": [
      "number may not be changed on non-configurable jobs"
    ]
  }
}

stderr:n
Status: 422 Unprocessable Entity
```

**Comment by kamoljan** [comment]
Any update?

**Comment by abbyachau** [comment]
Hi, just seeing this now - sorry about that. We've deprecated this repo in favour of https://github.com/pivotal-cf/pcf-pipelines. Please look for us there, thanks. v17 should work with 1.11.x. Please create a new issue in the new repo if you have any questions, thanks.

**Comment by kamoljan** [comment]
@abbyachau thank you for your follow-up!
